image: node:latest

stages:
  - merge
  - test
  - canary
  - prerelease
  - release

cache:
  paths:
    - node_modules

.testsetup: &testsetup
  services:
    - nativecode/test-radarr:latest
    - nativecode/test-sonarr:latest
  script:
    - .citools/wait-for ${HOSTNAME} 7878
    - .citools/wait-for ${HOSTNAME} 8989

before_script:
  - git submodule update --init -- .citools
  - npm ci
  - source .ci-env
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

merge:
  <<: *testsetup
  stage: merge
  script:
    - npm build
  except:
    - tags
  only:
    - merge_request

test:
  <<: *testsetup
  stage: test
  script:
    - npm test
  except:
    - develop
    - master
    - /feature\/*/
    - tags

canary:
  <<: *testsetup
  stage: canary
  script:
    - npm run canary
  except:
    - develop
    - master
    - tags
  only:
    - /feature\/*/

prerelease:
  <<: *testsetup
  stage: prerelease
  script:
    - npm run pre-release
  except:
    - tags
  only:
    - develop

release:
  <<: *testsetup
  stage: release
  script:
    - npm run release
  except:
    - tags
  only:
    - master
