export interface MediaInfo {
  containerFormat: string
  videoFormat: string
  videoCodecID: string
  videoProfile: string
  videoCodecLibrary: string
  videoBitrate: number
  videoBitDepth: number
  videoMultiViewCount: number
  videoColourPrimaries: string
  videoTransferCharacteristics: string
  width: number
  height: number
  audioFormat: string
  audioCodecID: string
  audioCodecLibrary: string
  audioAdditionalFeatures: string
  audioBitrate: number
  runTime: string
  audioStreamCount: number
  audioChannels: number
  audioChannelPositions: string
  audioChannelPositionsText: string
  audioProfile: string
  videoFps: number
  audioLanguages: string
  subtitles: string
  scanType: string
  schemaRevision: number
}
