#!/bin/bash

eval $(ssh-agent -s)

if [ ! -d ~/.ssh ]; then
  mkdir -p ~/.ssh
  chmod 0700 ~/.ssh
fi

echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null

git config --global user.email "opensource@nativecode.com"
git config --global user.name "automaton"
