#!/bin/bash

echo "** Setting git author"
git config --global user.email "opensource@nativecode.com"
git config --global user.name "automaton"

echo "** ssh-remote"
npx ssh-remote

echo "** Checkout ${CI_COMMIT_REF_NAME}"
git checkout ${CI_COMMIT_REF_NAME}
git checkout package.json

git status
