#!/bin/bash

git config --global user.email "opensource@nativecode.com"
git config --global user.name "automaton"

git checkout ${CI_COMMIT_REF_NAME}
git checkout package.json

git remote set-url origin git@git.nativecode.net:nativecode/media-clients.git
