#!/bin/bash

HOST=$1
PORT=$2

echo "Waiting for ${HOST}:${PORT} to be available..."

while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' ${HOST}:${PORT})" != "200" ]]; do
  sleep 5
done

echo "Found ${HOST}:${PORT}"
